# Generated by Django 5.0.7 on 2024-07-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_alter_post_options_remove_post_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="comment_files/"),
        ),
    ]
