# Generated by Django 5.0.7 on 2024-08-07 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_alter_comment_options_remove_comment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
